# Travis CI configuration file to run the µOS++ tests.

os:
  - linux
  # - osx

# Use the new Debian 14 containers.
dist: trusty
sudo: false

# For more clang versions: http://apt.llvm.org
# Unfortunately clang is not yet reliable on linux, it uses GCC headers,
# and it might get the wrong ones.
# The 32-bits libraries are required by the arm-none-eabi distribution.
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main' 
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main' 
        key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - g++-5
      - g++-6
      - clang-3.8
      - clang-3.9
      - lib32z1 lib32ncurses5 lib32bz2-1.0

osx_image: xcode8.2

language: cpp

git:
  # Limit the clone depth; default is 50.
  depth: 3

env:
  global:
    - SCRIPT_SYNTH="synthetic-posix-tests-micro-os-plus/scripts/travis.sh"
    - SCRIPT_F4DISCO="f4discovery-tests-micro-os-plus/scripts/travis.sh"

before_install:
  # - bash "${SCRIPT_SYNTH}" before_install
  - bash "${SCRIPT_F4DISCO}" before_install

# Skip the install step.
# install: true

# `--develop` will pull the `develop` branch, where available.
before_script:
  # - bash "${SCRIPT_SYNTH}" before_script --develop
  - bash "${SCRIPT_F4DISCO}" before_script --develop

script:
  # - bash "${SCRIPT_SYNTH}" script
  - bash "${SCRIPT_F4DISCO}" script

# Unused, kept for just in case.

# after_success:
#  - bash "${SCRIPT_SYNTH}" after_success

# after_failure:
#   - bash "${SCRIPT_SYNTH}" after_failure

# Deploy via script not functional (or not understood).
# deploy:
#  provider: script
#  script: bash scripts/travis.linux.sh deploy
#  on:
#    branch: master
  
# after_script:
#   - bash "${SCRIPT_SYNTH}" after_script
