# Travis CI configuration file to run the µOS++ tests.

os:
  - linux
  # - osx

# Use the new Debian 14 containers.
dist: trusty
sudo: true

# For more clang versions: http://apt.llvm.org
addons:
  apt:
    sources:
    # - ppa:jonathonf/gcc
    - ubuntu-toolchain-r-test
    - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
    packages:
    - g++-5
    - g++-6
    - clang-3.9


osx_image: xcode8.2

language: c++

git:
  # Limit the clone depth; default is 50.
  depth: 3

before_install:
  - bash synthetic-posix-tests-micro-os-plus/scripts/travis.sh before_install

# Skip the install step.
install: true

before_script:
  - bash synthetic-posix-tests-micro-os-plus/scripts/travis.sh before_script

script:
  - bash synthetic-posix-tests-micro-os-plus/scripts/travis.sh script

# -----------------------------------------------------------------------------
# Unused.

# after_success:
#  - bash scripts/travis.linux.sh after_success

# after_failure:
#  - bash scripts/travis.linux.sh after_failure

# Deploy via script not functional (or not understood).
# deploy:
#  provider: script
#  script: bash scripts/travis.linux.sh deploy
#  on:
#    branch: master
  
# after_script:
#  - bash scripts/travis.linux.sh after_script
